#!/usr/bin/env bash
#
# feodo-c2ip-fetch.sh — download the abuse.ch Feodo Tracker C2 IP blocklist and
# emit an nginx include for ngx_http_sentinel_module's sentinel_c2ip_deny
# directive.
#
# The abuse.ch Feodo Tracker feed (https://feodotracker.abuse.ch/blocklist/) is
# a curated set of IPv4 addresses of confirmed botnet command-and-control (C2)
# servers (Dridex, Emotet, TrickBot, QakBot, ...). An inbound client whose IP is
# known C2 infrastructure is high-confidence malicious. Pair it with:
#
#     sentinel_weight_c2ip 80;
#     include /etc/nginx/sentinel-c2ip-deny.conf;   # generated by this script
#
# Run from cron (daily is plenty) and reload nginx only when the output actually
# changed:
#
#     0 4 * * *  /opt/.../feodo-c2ip-fetch.sh -o /etc/nginx/sentinel-c2ip-deny.conf \
#                  && systemctl reload nginx
#
# Exit codes: 0 = file written/updated, 10 = unchanged (no reload needed),
# non-zero = error (the existing output is left untouched — fail-safe).

set -euo pipefail

FEED_URL="${FEODO_C2IP_URL:-https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt}"
OUT=""
MAX_IP="${FEODO_C2IP_MAX:-50000}"   # sanity cap; a truncated/garbage feed won't blow up the config

usage() {
    cat >&2 <<EOF
usage: $0 -o <output.conf> [-u <feed-url>]

  -o FILE   write the generated nginx include here (required)
  -u URL    override the feed URL (default: $FEED_URL)

Emits a single 'sentinel_c2ip_deny <ip> <ip> ...;' statement wrapped so it can
be 'include'd inside an http/server/location block. Atomic write + change
detection: exits 10 (no change) when the new content matches the existing file.
EOF
    exit 2
}

while getopts "o:u:h" opt; do
    case "$opt" in
        o) OUT="$OPTARG" ;;
        u) FEED_URL="$OPTARG" ;;
        h|*) usage ;;
    esac
done

[ -n "$OUT" ] || usage

tmp_raw="$(mktemp)"
tmp_out="$(mktemp)"
trap 'rm -f "$tmp_raw" "$tmp_out"' EXIT

# Download. Fail-safe: any curl error aborts before touching $OUT.
if ! curl -fsSL --max-time 60 "$FEED_URL" -o "$tmp_raw"; then
    echo "feodo-c2ip-fetch: download failed from $FEED_URL" >&2
    exit 1
fi

# The recommended blocklist is plain text: # comment lines, then one IPv4 per
# line. Keep only well-formed dotted-quad IPv4 (each octet 0-255), dedup.
mapfile -t ips < <(
    grep -v '^[[:space:]]*#' "$tmp_raw" \
      | tr -d '\r' \
      | grep -oE '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' \
      | awk -F. '$1<=255 && $2<=255 && $3<=255 && $4<=255' \
      | sort -u
)

count="${#ips[@]}"

if [ "$count" -eq 0 ]; then
    echo "feodo-c2ip-fetch: feed parsed to 0 IPs (format change?) — aborting, $OUT untouched" >&2
    exit 1
fi

if [ "$count" -gt "$MAX_IP" ]; then
    echo "feodo-c2ip-fetch: $count IPs exceeds cap $MAX_IP — aborting (set FEODO_C2IP_MAX to override)" >&2
    exit 1
fi

{
    echo "# Generated by feodo-c2ip-fetch.sh from $FEED_URL"
    echo "# abuse.ch Feodo Tracker C2 IP blocklist (botnet C2 infrastructure). DO NOT EDIT BY HAND."
    echo "# $count IPs. Include inside an http/server/location block:"
    echo "#     sentinel_weight_c2ip 80;"
    echo "#     include $OUT;"
    echo "sentinel_c2ip_deny"
    for ip in "${ips[@]}"; do
        printf '    %s\n' "$ip"
    done
    echo "    ;"
} > "$tmp_out"

# Change detection: skip the reload churn when nothing moved. Compare only the
# directive body (ignore the header comment, which is stable anyway).
if [ -f "$OUT" ] && diff -q \
        <(grep -v '^#' "$OUT" 2>/dev/null) \
        <(grep -v '^#' "$tmp_out") >/dev/null 2>&1; then
    echo "feodo-c2ip-fetch: unchanged ($count IPs)"
    exit 10
fi

# Atomic replace.
install -m 0644 "$tmp_out" "$OUT.tmp.$$"
mv -f "$OUT.tmp.$$" "$OUT"
echo "feodo-c2ip-fetch: wrote $OUT ($count IPs)"
exit 0
