#!/usr/bin/env bash
#
# sslbl-ja3-fetch.sh — download the abuse.ch SSLBL JA3 blacklist and emit an
# nginx include for ngx_http_sentinel_module's sentinel_ja3_deny directive.
#
# The abuse.ch SSLBL feed (https://sslbl.abuse.ch/blacklist/) is a curated set
# of JA3 MD5 fingerprints of known malware / botnet C2 TLS clients. Pair it
# with the ssl-fingerprint module's $ssl_fingerprint_ja3_hash:
#
#     ssl_fingerprint on;
#     sentinel_ja3 $ssl_fingerprint_ja3_hash;
#     include /etc/nginx/sentinel-ja3-deny.conf;   # generated by this script
#
# Run from cron (daily is plenty — the feed updates a few times a day) and
# reload nginx only when the output actually changed:
#
#     0 4 * * *  /opt/.../sslbl-ja3-fetch.sh -o /etc/nginx/sentinel-ja3-deny.conf \
#                  && systemctl reload nginx
#
# Exit codes: 0 = file written/updated, 10 = unchanged (no reload needed),
# non-zero = error (the existing output is left untouched — fail-safe).

set -euo pipefail

FEED_URL="${SSLBL_JA3_URL:-https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv}"
OUT=""
MAX_FP="${SSLBL_JA3_MAX:-5000}"   # sanity cap; a truncated/garbage feed won't blow up the config

usage() {
    cat >&2 <<EOF
usage: $0 -o <output.conf> [-u <feed-url>]

  -o FILE   write the generated nginx include here (required)
  -u URL    override the feed URL (default: $FEED_URL)

Emits a single 'sentinel_ja3_deny <hash> <hash> ...;' statement wrapped so it
can be 'include'd inside an http/server/location block. Atomic write + change
detection: exits 10 (no change) when the new content matches the existing file.
EOF
    exit 2
}

while getopts "o:u:h" opt; do
    case "$opt" in
        o) OUT="$OPTARG" ;;
        u) FEED_URL="$OPTARG" ;;
        h|*) usage ;;
    esac
done

[ -n "$OUT" ] || usage

tmp_csv="$(mktemp)"
tmp_out="$(mktemp)"
trap 'rm -f "$tmp_csv" "$tmp_out"' EXIT

# Download. Fail-safe: any curl error aborts before touching $OUT.
if ! curl -fsSL --max-time 60 "$FEED_URL" -o "$tmp_csv"; then
    echo "sslbl-ja3-fetch: download failed from $FEED_URL" >&2
    exit 1
fi

# The CSV is: # comment lines, then  ja3_md5,FirstSeen,LastSeen,Listingreason
# Extract column 1 where it is exactly 32 lower/upper hex chars (a JA3 MD5).
mapfile -t fps < <(
    grep -v '^[[:space:]]*#' "$tmp_csv" \
      | cut -d',' -f1 \
      | tr -d '"' \
      | grep -iE '^[0-9a-f]{32}$' \
      | sort -u
)

count="${#fps[@]}"

if [ "$count" -eq 0 ]; then
    echo "sslbl-ja3-fetch: feed parsed to 0 fingerprints (format change?) — aborting, $OUT untouched" >&2
    exit 1
fi

if [ "$count" -gt "$MAX_FP" ]; then
    echo "sslbl-ja3-fetch: $count fingerprints exceeds cap $MAX_FP — aborting (set SSLBL_JA3_MAX to override)" >&2
    exit 1
fi

{
    echo "# Generated by sslbl-ja3-fetch.sh from $FEED_URL"
    echo "# abuse.ch SSLBL JA3 blacklist (malware/C2 TLS clients). DO NOT EDIT BY HAND."
    echo "# $count fingerprints. Include inside an http/server/location block:"
    echo "#     sentinel_ja3 \$ssl_fingerprint_ja3_hash;"
    echo "#     include $OUT;"
    echo "sentinel_ja3_deny"
    for fp in "${fps[@]}"; do
        printf '    %s\n' "$fp"
    done
    echo "    ;"
} > "$tmp_out"

# Change detection: skip the reload churn when nothing moved. Compare only the
# directive body (ignore the header comment, which is stable anyway).
if [ -f "$OUT" ] && diff -q \
        <(grep -v '^#' "$OUT" 2>/dev/null) \
        <(grep -v '^#' "$tmp_out") >/dev/null 2>&1; then
    echo "sslbl-ja3-fetch: unchanged ($count fingerprints)"
    exit 10
fi

# Atomic replace.
install -m 0644 "$tmp_out" "$OUT.tmp.$$"
mv -f "$OUT.tmp.$$" "$OUT"
echo "sslbl-ja3-fetch: wrote $OUT ($count fingerprints)"
exit 0
